version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    restart: always
    ports:
      - 3042:3042
    depends_on:
      - mongodb
    environment:
       MONGO_URI: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/admin

volumes:
  mongodb_data:
